{% set name = "PhosphorosCore" %}
{% set version = "1.3.0" %}
{% set build_number = 0 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: {{ version }} 
    git_url: https://github.com/astrorama/PhosphorosCore.git 

build:
    number: {{ build_number }}
    run_exports:
      - {{ pin_subpackage('phosphoroscore', max_pin='x.x.x') }}

test:
    commands:
        - $PREFIX/bin/PhosphorosComputeModelSed --help

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cython                             # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
    host:
        - python
        - boost-cpp
        - alexandria ==2.26.0
        - cfitsio >=3.470
        - CCfits >=2.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('astropy', min_pin='x.x', max_pin='x') }}

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

