{% set name = "PhosphorosCore" %}
{% set version = "0.18" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: develop
    git_url: https://{{ environ.get('GIT_USER', '') }}@gitlab.euclid-sgs.uk/PF-PHZ/PhosphorosCore.git
    patches:
      - alexandria_2.17.1.patch

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    run_exports:
      - {{ pin_subpackage('phosphoroscore', max_pin='x.x.x') }}

test:
    commands:
        - $PREFIX/bin/PhosphorosComputeModelSed --help

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
    host:
        - python
        - boost-cpp
        - elements ==5.12
        - alexandria ==2.19
        - cfitsio >=3.470
        - CCfits >=2.5
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits') }} 
        - {{ pin_compatible('astropy') }}

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

