package:
    name: phosphoroscore 
    version: "0.15"

source:
    git_rev: develop
    git_url: https://{{ environ.get('GIT_USER', '') }}@gitlab.euclid-sgs.uk/PF-PHZ/PhosphorosCore.git

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

test:
    commands:
        - $PREFIX/bin/PhosphorosComputeModelSed --help

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.8
        - alexandria ==2.15
        - boost-cpp ==1.70
        - cfitsio
        - CCfits
        - python
        - pytest
    run:
        - elements ==5.8
        - alexandria ==2.15
        - boost-cpp ==1.70
        - cfitsio
        - CCfits
        - astropy

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

