package:
    name: phosphoroscore 
    version: "0.15"

source:
    url: https://bintray.com/astrorama/archive/download_file?file_path=PhosphorosCore-0.15.tar.gz

build:
    number: 1

test:
    commands:
        - $PREFIX/bin/PhosphorosComputeRedshifts --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.8
        - alexandria ==2.15
        - boost >=1.69
        - cfitsio
        - CCfits
        - python
        - pytest
    run:
        - elements ==5.8
        - alexandria ==2.15
        - boost >=1.69
        - cfitsio
        - CCfits
        - astropy

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

