package:
    name: phosphoroscore 
    version: "0.17"

source:
    git_rev: develop
    git_url: https://{{ environ.get('GIT_USER', '') }}@gitlab.euclid-sgs.uk/PF-PHZ/PhosphorosCore.git

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

test:
    commands:
        - $PREFIX/bin/PhosphorosComputeModelSed --help

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - elements ==5.10
        - alexandria ==2.17
        - boost-cpp ==1.70
        - cfitsio >=3.470
        - CCfits >=2.5
        - python >=3.8
        - pytest >=5.3
    run:
        - boost-cpp ==1.70
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('CCfits') }} 
        - {{ pin_compatible('astropy') }}

about:
    home: http://isdc.unige.ch/euclid/phosphoros/
    license: LGPL
    summary: A photometric redshift determination tool based on a template fitting method.

